import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@web3modal/react";

const Home: NextPage = () => {
  // const videoContent = (
  //   <Image>

  //   </Image>

  // )
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ConnectButton /> */}

      <main className={styles.main}>
        <h3>
          Web3Modal is an elegantly simple yet powerful library that helps you
          manage your multi-chain wallet connection flows, all in one place.
          Designed with both developers and end users in mind, it is easy to
          integrate and customize, bringing to life a sleek and unique
          experience.{" "}
        </h3>
      </main>
    </div>
  );
};

export default Home;
